const STATUS_ACTIVE = "Active";
const STATUS_INACTIVE = "Inactive";
const STATUS_DISCHARGED = "Discharged";
const STATUS_PENDING = "Pending";

const USER_STATUS_OPTIONS = [STATUS_ACTIVE, STATUS_INACTIVE];
const PATIENT_STATUS_OPTIONS = [
  STATUS_ACTIVE,
  STATUS_DISCHARGED,
  STATUS_PENDING,
];

const ALL_STATUSES = "All";
const FAVORITES_FILTER = "Favorites";
const NON_FAVORITES_FILTER = "Non-favorites";

export {
  STATUS_ACTIVE,
  STATUS_INACTIVE,
  STATUS_DISCHARGED,
  STATUS_PENDING,
  USER_STATUS_OPTIONS,
  PATIENT_STATUS_OPTIONS,
  ALL_STATUSES,
  FAVORITES_FILTER,
  NON_FAVORITES_FILTER,
};
