const STATUS_ACTIVE = "Active";
const STATUS_INACTIVE = "Inactive";
const STATUS_PENDING = "Pending";

const USER_STATUS_OPTIONS = [STATUS_ACTIVE, STATUS_INACTIVE];
const PATIENT_STATUS_OPTIONS = [
  STATUS_ACTIVE,
  STATUS_INACTIVE,
  STATUS_PENDING,
];

export {
  STATUS_ACTIVE,
  STATUS_INACTIVE,
  STATUS_PENDING,
  USER_STATUS_OPTIONS,
  PATIENT_STATUS_OPTIONS,
};
