const STORAGE_SCHEMA_VERSION = 2;
const LEGACY_STORAGE_SCHEMA_VERSION = 0;
const MAX_STORED_ACTIVITIES = 100;

export {
  STORAGE_SCHEMA_VERSION,
  LEGACY_STORAGE_SCHEMA_VERSION,
  MAX_STORED_ACTIVITIES,
};
